name: Update PTT Trends (Python)

on:
  schedule:
    # 每 10 分鐘執行 (每小時第 1、11、21、31、41、51 分鐘)
    - cron: '1,11,21,31,41,51 * * * *'
  workflow_dispatch:
    # 允許手動觸發

jobs:
  update-ptt-trends:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
        
    - name: Install dependencies
      run: |
        uv sync
        
    - name: Set up Chrome
      uses: browser-actions/setup-chrome@latest
      
    - name: Run PTT Trends scraper
      run: |
        uv run python src/ptt_trends.py
        
    - name: Check if data changed
      id: verify-changed-files
      run: |
        if [[ `git status --porcelain` ]]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Commit and push if changed
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/ptt-trends.json
        git commit -m "📰 Update PTT Trends data - $(date '+%Y-%m-%d %H:%M:%S')" || exit 0
        git push
