name: Update BBC Trends (Python)

on:
    schedule:
        - cron: '15,45 * * * *' # 每小時第 15 和 45 分鐘執行
    workflow_dispatch:

jobs:
    update:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.11'

            - name: Install uv
              uses: astral-sh/setup-uv@v4

            - name: Install dependencies
              working-directory: trend-scraper-python
              run: uv sync

            - name: Run BBC Scraper
              working-directory: trend-scraper-python
              run: uv run python src/main.py bbc

            - name: Commit and Push Results
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  git config --global user.name "Gary Lin"
                  git config --global user.email "garylin0969@gmail.com"

                  # 先保存爬蟲的新資料
                  cp trend-scraper-python/data/bbc-trends.json /tmp/bbc-trends.json

                  # 拉取最新的程式碼
                  git pull origin main

                  # 把新爬到的資料覆蓋回去
                  cp /tmp/bbc-trends.json trend-scraper-python/data/bbc-trends.json

                  # 提交並推送
                  git add trend-scraper-python/data/bbc-trends.json
                  git commit -m "update bbc trends (python) [CI] $(TZ=Asia/Taipei date '+%Y-%m-%d %H:%M:%S')" || echo "Nothing to commit"
                  git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
